/// Reservation flow constants (airports list, etc.).
class ReservationConstants {
  ReservationConstants._();

  /// Airport list for Airport Tab
  static const List<(String id, String name)> airports = [
    ('BWI', 'Baltimore Washington International Airport (BWI)'),
    ('BWI_TRAIN', 'BWI TRAIN Station'),
    ('IAD', 'Dulles International Airport (IAD)'),
    ('GREENBELT', 'Greenbelt Metro'),
    ('JFK', 'John F. Kennedy International Airport (JFK)'),
    ('LGA', 'LaGuardia Airport (LGA)'),
    ('LNS', 'Lancaster Airport (LNS)'),
    ('EWR', 'Newark Liberty International Airport (EWR)'),
    ('PENN_BALTIMORE', 'Penn Station, Baltimore'),
    ('PHL', 'Philadelphia International Airport (PHL)'),
    ('DCA', 'Reagan Washington National Airport (DCA)'),
    ('RIC', 'Richmond International Airport (RIC)'),
    ('UNION_DC', 'Union Station, D.C'),
    ('BWI_SIGNATURE', 'Baltimore Signature Airport'),
    ('IAD_SIGNATURE', 'IAD Signature Airport'),
    ('BWI_CRUISE', 'Baltimore Cruise Port'),
  ];

  /// Airlines list for dropdown
  static const List<String> airlines = [
    'Abacus International',
    'ABX Air',
    'AccesRail and Partner Railways',
    'ACT Airlines',
    'Adria Airways',
    'Aegean Airlines',
    'Aer Arann',
    'Aer Lingus',
    'Aero-Charter Airlines',
    'Aerocon',
    'Aerodynamics',
    'Aeroflot Russian Airlines',
    'AeroGal',
    'Aerolíneas Argentinas',
    'Aerolíneas MAS',
    'Aerolinea Principal Chile',
    'Aerolineas Sosa',
    'Aeroméxico Connect',
    'Aeromar Airlines',
    'Aeromexico',
    'Aeropelican Air Services',
    'Aerosvit Airlines',
    'Aerotel',
    'Afghan Jet International Airlines',
    'Africa West',
    'African express Airways',
    'Afriqiyah Airways',
    'Aigle Azur',
    'Air Algérie',
    'Air Alliance',
    'Air Alps',
    'Air Alsie',
    'Air Arabia',
    'Air Arabia Egypt',
    'Air Arabia Maroc',
    'Air Armenia',
    'Air Asia Zest',
    'Air Astana',
    'Air Austral',
    'Air Bagan',
    'Air Bashkortostan',
    'Air Bishkek',
    'Air Botswana',
    'Air Burkina',
    'Air Busan',
    'Air Cairo',
    'Air Caledonie',
    'Air Canada',
    'Air Canada Rouge',
    'Air Caraibes',
    'Air China',
    'Air Choice One',
    'Air Corsica',
    'Air Cote D\'Ivoire',
    'Air Creebec',
    'Air Do',
    'Air Dolomiti',
    'Air Europa',
    'Air Excursions',
    'Air France',
    'Air Hong Kong - AHK',
    'Air Iceland',
    'Air Incheon',
    'Air India Charters Limited',
    'Air India Limited',
    'Air Indus',
    'Air Inuit',
    'Air Italy',
    'Air Japan',
    'Air KBZ',
    'Air Koryo',
    'Air Labrador',
    'Air Lituanica',
    'Air Macau',
    'Air Madagascar',
    'Air Malawi',
    'Air Malta',
    'Air Manas',
    'Air Mauritius',
    'Air Mediterranee',
    'Air Mobility Command (AMC)',
    'Air Moldova',
    'Air Namibia',
    'Air New Zealand',
    'Air Niamey',
    'Air Niugini',
    'Air North',
    'Air Nostrum',
    'Air One',
    'Air Onix',
    'Air Rarotonga',
    'Air Seychelles',
    'Air Sinai',
    'Air Sunshine',
    'Air Tahiti',
    'Air Tahiti Nui',
    'Air Tanzania',
    'Air Timor',
    'Air Tindi',
    'Air Transat',
    'Air Uganda',
    'Air Urga',
    'Air Vanuatu',
    'Air Via',
    'Air Zimbabwe',
    'AirAsia',
    'AirAsia Japan',
    'AirAsia Philippines',
    'AirAsia X',
    'AirBaltic',
    'airberlin',
    'AirBlue',
    'Aircalin',
    'Aircompany Kyrgyzstan',
    'Aires',
    'AirExplore',
    'Airnorth Regional',
    'AirTran Airways',
    'AIS Airlines',
    'AK Bars Aero',
    'Aklak Air',
    'Alaska Airlines',
    'Alitalia',
    'All Nippon Airways',
    'Allegiant Air',
    'American Airlines',
    'American Eagle',
    'Ameriflight',
    'Amerijet International',
    'ANA Wings',
    'Angara Airlines',
    'Ariana Afghan Airlines',
    'Arik Air',
    'Arkia - Israeli Airlines',
    'Armavia',
    'Asiana Airlines',
    'ASKY Airlines',
    'Atlantic Airways',
    'Atlas Air',
    'Atlasjet Airlines',
    'Austrian',
    'Avianca',
    'Azerbaijan Airlines',
    'Azul Linhas Aereas Brasileiras',
    'BA Cityflyer',
    'Bahamasair',
    'Bangkok Airways',
    'Batik Air',
    'Bearskin Airlines',
    'Belavia',
    'Berjaya Air',
    'Biman Bangladesh Airlines',
    'Binter Canarias',
    'Blue Bird Airways',
    'Blue Panorama Airlines',
    'Boliviana de Aviacion',
    'British Airways',
    'Brussels Airlines',
    'Bulgaria Air',
    'Cambodia Angkor Air',
    'Canadian North',
    'Cape Air',
    'Caribbean Airlines',
    'Cathay Pacific Airways',
    'Cayman Airways',
    'CEBU Pacific Air',
    'Central Mountain Air',
    'Chalair Aviation',
    'Chengdu Airlines',
    'China Airlines',
    'China Eastern Airlines',
    'China Southern Airlines',
    'Cityjet',
    'Comair',
    'Compass Airlines',
    'Condor',
    'Copa Airlines',
    'Corendon Airlines',
    'Corsair International',
    'Croatia Airlines',
    'Cubana',
    'Cyprus Airways',
    'Czech Airlines',
    'Dana Airlines',
    'Delta Airlines',
    'Dragonair',
    'Druk Air',
    'Eastar Jet',
    'Eastern Airways',
    'easyJet',
    'Edelweiss Air',
    'Egyptair',
    'El Al Israel Airlines',
    'Emirates',
    'Endeavor Air',
    'Estonian Air',
    'Ethiopian Airlines',
    'Etihad Airways',
    'Eurowings',
    'EVA Air',
    'ExpressJet',
    'Far Eastern Air Transport',
    'Fastjet',
    'FedEx',
    'Fiji Airways',
    'Finnair',
    'Flair Airlines',
    'Flybe',
    'Fly Jamaica Airways',
    'Freebird Airlines',
    'Frontier Airlines',
    'Fuji Dream Airlines',
    'Garuda',
    'Georgian Airways',
    'Germanwings',
    'GoAir',
    'Gol Linhas Aéreas Inteligentes',
    'Gulf Air',
    'Hainan Airlines',
    'Hawaiian Airlines',
    'Hebei Airlines',
    'Hong Kong Airlines',
    'Hong Kong Express',
    'HOP!',
    'Horizon Air',
    'Iberia',
    'Iberia Express',
    'IBEX Airlines',
    'Icelandair',
    'Indigo',
    'Indonesia AirAsia',
    'Interjet',
    'Iran Air',
    'Iran Aseman Airlines',
    'Island Air',
    'Israir Airlines',
    'Japan Airlines',
    'Jazeera Airways',
    'Jet Airways',
    'Jet2.com',
    'Jetblue Airways',
    'Jetstar Airways',
    'Jin Air',
    'Jordan Aviation',
    'Juneyao Airlines',
    'Kam-Air',
    'Kan Air',
    'Kenya Airways',
    'Kish Air',
    'KLM Royal Dutch Airlines',
    'Korean Air',
    'Kuwait Airways',
    'LAN Airlines',
    'LAN Argentina',
    'LAN Perú',
    'Lao Airlines',
    'LIAT',
    'Libyan Airlines',
    'Lion Airlines',
    'Loganair',
    'LOT Polish Airlines',
    'Lucky Air',
    'Lufthansa',
    'Luxair',
    'Mahan Air',
    'Malaysia Airlines',
    'Malindo Air',
    'Mandarin Airlines',
    'Martinair',
    'MASwings',
    'MEA - Middle East Airlines',
    'Meridiana fly',
    'Mesa Airlines',
    'MIAT Mongolian Airlines',
    'Monarch Airlines',
    'Montenegro Airlines',
    'Nasair',
    'Nepal Airlines',
    'Nesma Airlines',
    'Nile Air',
    'Nok Air',
    'Nordwind Airlines',
    'Norwegian',
    'Nouvelair',
    'Novoair',
    'Oman Air',
    'Onur Air',
    'Olympic Air',
    'Pakistan International Airlines',
    'Pegasus Airlines',
    'Philippine Airlines',
    'Porter Airlines',
    'Precision Air',
    'Qantas',
    'Qatar Airways',
    'Ryanair',
    'S7 Airlines',
    'Saudia',
    'Scoot',
    'Shenzhen Airlines',
    'Sichuan Airlines',
    'SilkAir',
    'Singapore Airlines',
    'Sky Airline',
    'SkyWest Airlines',
    'South African Airways',
    'Southwest Airlines',
    'SpiceJet',
    'Spirit Airlines',
    'Spring Airlines',
    'SriLankan Airlines',
    'SunExpress',
    'Sunwing Airlines',
    'SWISS',
    'Syrianair',
    'TAP Portugal',
    'TAROM',
    'Thai Airways International',
    'Tigerair',
    'Transavia',
    'Turkish Airlines',
    'Ukraine International Airlines',
    'United Airlines',
    'US Airways',
    'Uzbekistan Airways',
    'Vietjet Air',
    'Vietnam Airlines',
    'Virgin Atlantic',
    'Volaris',
    'Volotea',
    'Vueling',
    'WestJet',
    'Wizz Air',
    'Xiamen Airlines',
    'Yamal Airlines',
    'Yeti Airlines',
  ];
}
